import data from './book.json';
import { FILM_URL, FILM_CAPTIONS, FILM_POSTER } from '../../lib/media/film-delivery.js';

/**
 * The Gift of the Magi, as a pack.
 *
 * `book.json` is what the extractor produces — the story, the teaching,
 * the characters, the translations. This file is the rest of the pack:
 * where its media actually sits once it is built and uploaded.
 *
 * That split matters. The extractor's output should be portable data
 * with no deployment in it, and the paths below are deployment: they
 * depend on how `tools/copy-assets.mjs` lays the files out, not on
 * anything O. Henry wrote.
 *
 * Relative, with no leading slash — see MEDIA_BASE in reader/beats.js.
 * itch serves a game from a nested path, so "/magi-audio/x.mp3"
 * resolves against the domain root and 404s for every clip.
 */

/** @type {import('../../lib/types.js').Book} */
export default {
  ...data,
  meta: { ...data.meta, author: 'O. Henry' },
  cinematicFilm: FILM_URL,
  cinematicCaptions: FILM_CAPTIONS,
  cinematicPoster: FILM_POSTER,
  cinematicLoop: false,
  credits: {
    score: 'audio/magi-score.mp3',
    scoreCue: 138,
    cards: [
      {
        kicker: 'Written by',
        title: 'O. Henry',
        text: 'William Sydney Porter wrote about ordinary New Yorkers with warmth, mischief, and a sharp eye for reversals.',
        image: 'art/3ded1a00f03753bd.webp',
        alt: 'An open book beside an oil lamp and pocket watch, overlooking a snowy city.',
      },
      {
        kicker: 'Della Dillingham Young',
        title: 'The giver with one dollar and eighty-seven cents',
        text: 'She turns the treasure she can sell into the gift she most wants to give.',
        image: 'art/storyboard/s1/s1-a-counting.jpg',
        alt: 'Della counts a small pile of coins by lamplight.',
      },
      {
        kicker: 'James Dillingham Young',
        title: 'The keeper of the gold watch',
        text: 'Jim enters carrying the other half of the story—and the sacrifice Della cannot yet see.',
        image: 'art/806b2bd4d4fb3e99.webp',
        alt: 'Jim writes at a bare table in a dimly lit room.',
      },
      {
        kicker: 'Madame Sofronie',
        title: 'Hair goods of all kinds',
        text: 'Her brisk transaction turns Della’s beautiful hair into twenty dollars and sets the gifts in motion.',
        image: 'art/storyboard/s5/s5-b-sofronie-transaction.jpg',
        alt: 'Madame Sofronie examines Della’s long brown hair in the upstairs shop.',
      },
      {
        kicker: 'First appearance',
        title: 'December 10, 1905',
        text: 'The story appeared in the New York Sunday World on December 10, 1905.',
        image: 'art/e0232928da83eab8.webp',
        alt: 'Della studies her newly shortened hair in a mirror.',
      },
      {
        kicker: 'On the bookshelf',
        title: 'One story among The Four Million',
        text: 'In 1906 it joined O. Henry’s collection of twenty-five New York stories—tales that treated ordinary lives as worth noticing.',
        image: 'art/5bdc90a6f392d3c2.webp',
        alt: 'A closed book rests by a snowy New York window.',
      },
      {
        kicker: 'The final credit',
        title: 'Della and Jim—the Magi',
        text: 'Their gifts lose their use. Their giving keeps its meaning. O. Henry calls them the wisest.',
        image: 'art/3ded1a00f03753bd.webp',
        alt: 'An open book, oil lamp, and pocket watch at a winter window.',
      },
    ],
  },
  storyboard: {
    's1-0': {
      start: 'art/storyboard/s1/s1-a-counting.jpg',
      clip: 'video/storyboard/s1/s1-a-counting.mp4',
      clipStart: 0,
      alt: 'Della counting a meager pile of coins in her worn furnished flat.',
      shot: 'medium-wide room view moving toward the table',
      camera: 'restrained slow push',
      action: 'Della finishes counting the small pile',
      mood: 'concentration turning to dread',
      duration: 1.984,
      status: 'approved',
    },
    's1-1': {
      start: 'art/storyboard/s1/s1-a-counting.jpg',
      clip: 'video/storyboard/s1/s1-a-counting.mp4',
      clipStart: 1.984,
      alt: 'Della sitting in silence with the inadequate pile of coins.',
      shot: 'continuation of the room view',
      camera: 'restrained slow push',
      action: 'her hands settle beside the coins',
      mood: 'quiet finality',
      duration: 1.683,
      status: 'approved',
    },
    's1-2': {
      start: 'art/storyboard/s1/s1-a-counting.jpg',
      clip: 'video/storyboard/s1/s1-a-counting.mp4',
      clipStart: 3.667,
      alt: 'Della separating pennies into small counted groups.',
      shot: 'move into the hands-and-coins close view',
      camera: 'motivated cut, then nearly locked',
      action: 'her fingertips divide the pennies',
      mood: 'careful, weary arithmetic',
      duration: 2.017,
      status: 'approved',
    },
    's1-3': {
      start: 'art/storyboard/s1/s1-a-counting.jpg',
      clip: 'video/storyboard/s1/s1-a-counting.mp4',
      clipStart: 5.684,
      alt: 'Della counting pennies one and two at a time on the worn table.',
      shot: 'close view of the same hands and coins',
      camera: 'locked with slight natural drift',
      action: 'her fingers gather and recount the pennies',
      mood: 'patient sacrifice',
      duration: 2.316,
      status: 'approved',
    },
    's1-4': {
      start: 'art/storyboard/s1/s1-b-market.jpg',
      clip: 'video/storyboard/s1/s1-b-market.mp4',
      clipStart: 0,
      alt: 'Della bargaining carefully with a neighborhood shopkeeper.',
      shot: 'medium market-counter two-shot',
      camera: 'restrained push toward Della',
      action: 'Della holds her ground over a few coins',
      mood: 'determined embarrassment',
      duration: 3.667,
      status: 'approved',
    },
    's1-5': {
      start: 'art/storyboard/s1/s1-b-market.jpg',
      clip: 'video/storyboard/s1/s1-b-market.mp4',
      clipStart: 3.667,
      alt: 'Della enduring the embarrassment of bargaining for every penny.',
      shot: 'closer market-counter view',
      camera: 'slow push toward her expression',
      action: 'her flushed gaze lowers and steadies',
      mood: 'shame endured for a purpose',
      duration: 3,
      status: 'approved',
    },
    's1-6': {
      start: 'art/storyboard/s1/s1-b-market.jpg',
      clip: 'video/storyboard/s1/s1-b-market.mp4',
      clipStart: 6.667,
      alt: 'Della closing her hand protectively around the saved coins.',
      shot: 'waist-and-hands detail',
      camera: 'locked',
      action: 'she protects the coins and turns away',
      mood: 'discomfort accepted',
      duration: 2.333,
      status: 'approved',
    },
    's1-7': {
      start: 'art/storyboard/s1/s1-c-recount.jpg',
      clip: 'video/storyboard/s1/s1-c-recount.mp4',
      clipStart: 0,
      alt: 'Della beginning yet another count of the same small coin pile.',
      shot: 'three-quarter apartment view',
      camera: 'tiny restrained drift',
      action: 'her finger returns to the first coin',
      mood: 'arithmetic mixed with disbelief',
      duration: 1.919,
      status: 'approved',
    },
    's1-8': {
      start: 'art/storyboard/s1/s1-c-recount.jpg',
      clip: 'video/storyboard/s1/s1-c-recount.mp4',
      clipStart: 1.919,
      alt: 'Della facing the same inadequate total after counting again.',
      shot: 'same apartment composition',
      camera: 'almost imperceptible push',
      action: 'her hands become still beside the coins',
      mood: 'the same answer after three counts',
      duration: 1.984,
      status: 'approved',
    },
    's1-9': {
      start: 'art/storyboard/s1/s1-c-recount.jpg',
      clip: 'video/storyboard/s1/s1-c-recount.mp4',
      clipStart: 3.903,
      alt: 'The meager coins beneath a single modest Christmas sprig.',
      shot: 'apartment view with restrained Christmas detail',
      camera: 'subtle focus transition',
      action: 'attention shifts from the coins to Christmas',
      mood: 'a deadline arriving',
      duration: 1.72,
      status: 'approved',
    },
    's1-10': {
      start: 'art/storyboard/s1/s1-d-couch.jpg',
      clip: 'video/storyboard/s1/s1-d-couch.mp4',
      clipStart: 0,
      alt: 'Della looking from the coin table toward the shabby couch.',
      shot: 'medium-wide apartment view',
      camera: 'locked',
      action: 'her shoulders sink as she turns toward the couch',
      mood: 'exhausted surrender',
      duration: 1.841,
      status: 'approved',
    },
    's1-11': {
      start: 'art/storyboard/s1/s1-d-couch.jpg',
      clip: 'video/storyboard/s1/s1-d-couch.mp4',
      clipStart: 1.841,
      alt: 'Della collapsing onto the shabby little couch in private misery.',
      shot: 'medium side view',
      camera: 'gentle follow downward',
      action: 'she crosses the room and collapses sideways',
      mood: 'genuine private grief',
      duration: 2.713,
      status: 'approved',
    },
    's1-12': {
      start: 'art/storyboard/s1/s1-d-couch.jpg',
      clip: 'video/storyboard/s1/s1-d-couch.mp4',
      clipStart: 4.554,
      alt: 'Della lying collapsed on the couch with her hair still pinned.',
      shot: 'held medium side view',
      camera: 'locked',
      action: 'only a small shoulder movement from crying',
      mood: 'dry narration over real sadness',
      duration: 1.203,
      status: 'approved',
    },
    's1-13': {
      start: 'art/storyboard/s1/s1-d-couch-hold.jpg',
      alt: 'Della lying small and still on the worn couch in the furnished flat.',
      shot: 'held medium-wide interior',
      camera: 'still hold cut before the generated wall reveal',
      action: 'the room remains quiet around her',
      mood: 'reflection beyond the immediate sorrow',
      duration: 2.028,
      status: 'approved',
    },
    's1-14': {
      start: 'art/storyboard/s1/s1-e-reflection.jpg',
      clip: 'video/storyboard/s1/s1-e-reflection.mp4',
      clipStart: 0,
      alt: 'Della wiping beneath one tearful eye and taking a breath.',
      shot: 'medium close-up',
      camera: 'gentle slow push',
      action: 'she wipes a tear and gathers herself',
      mood: 'sadness with a trace of resilience',
      duration: 3.377,
      status: 'approved',
    },
    's1-15': {
      start: 'art/storyboard/s1/s1-e-reflection.jpg',
      clip: 'video/storyboard/s1/s1-e-reflection.mp4',
      clipStart: 3.377,
      alt: 'Della sniffing once as her expression becomes quietly composed.',
      shot: 'same close-up',
      camera: 'nearly locked',
      action: 'one small sniff and a restrained recovery',
      mood: 'dry humor without breaking sympathy',
      duration: 1.622,
      status: 'approved',
    },
    's2-0': {
      start: 'art/storyboard/s2/s2-a-flat-reveal.jpg',
      clip: 'video/storyboard/s2/s2-a-flat-reveal.mp4',
      clipStart: 0,
      alt: 'Della calming after her cry in the dim furnished flat.',
      shot: 'tearful close-up opening into the room',
      camera: 'slow continuous dolly backward',
      action: 'Della takes one quiet breath and grows still',
      mood: 'restrained sadness easing into observation',
      duration: 3.3,
      status: 'approved',
    },
    's2-1': {
      start: 'art/storyboard/s2/s2-a-flat-reveal.jpg',
      clip: 'video/storyboard/s2/s2-a-flat-reveal.mp4',
      clipStart: 3.3,
      alt: 'The camera beginning to reveal Della’s small furnished home.',
      shot: 'medium pullback',
      camera: 'slow continuous dolly backward',
      action: 'the shabby room enters the frame around Della',
      mood: 'an intimate invitation to look closely',
      duration: 1.2,
      status: 'approved',
    },
    's2-2': {
      start: 'art/storyboard/s2/s2-a-flat-reveal.jpg',
      clip: 'video/storyboard/s2/s2-a-flat-reveal.mp4',
      clipStart: 4.5,
      alt: 'A wider view of the Youngs’ worn eight-dollar-a-week flat.',
      shot: 'room-establishing medium wide',
      camera: 'slow continuous dolly backward',
      action: 'cheap furniture, worn carpet, and winter window become clear',
      mood: 'plainspoken poverty without caricature',
      duration: 1.8,
      status: 'approved',
    },
    's2-3': {
      start: 'art/storyboard/s2/s2-a-flat-reveal.jpg',
      clip: 'video/storyboard/s2/s2-a-flat-reveal.mp4',
      clipStart: 6.3,
      alt: 'The modest room fully visible around a quiet Della.',
      shot: 'wide interior',
      camera: 'pullback settling toward a locked frame',
      action: 'Della remains small and still amid the mismatched furniture',
      mood: 'dry narrative wit held inside genuine sympathy',
      duration: 1.5,
      status: 'approved',
    },
    's2-4': {
      start: 'art/storyboard/s2/s2-a-flat-reveal.jpg',
      clip: 'video/storyboard/s2/s2-a-flat-reveal.mp4',
      clipStart: 7.8,
      alt: 'The shabby flat held in a calm, honest wide view.',
      shot: 'final wide tableau',
      camera: 'nearly locked',
      action: 'the room’s worn details hold while Della composes herself',
      mood: 'O. Henry’s gentle irony and compassion',
      duration: 2.2,
      status: 'approved',
    },
    's2-5': {
      start: 'art/storyboard/s2/s2-b-vestibule.jpg',
      clip: 'video/storyboard/s2/s2-b-vestibule.mp4',
      clipStart: 0,
      alt: 'A cold, shabby downstairs vestibule with a broken letterbox.',
      shot: 'wide vestibule moving toward the fixtures',
      camera: 'slow continuous push in',
      action: 'the bent letterbox enters clear view',
      mood: 'observant poverty with dry humor',
      duration: 2.4,
      status: 'approved',
    },
    's2-6': {
      start: 'art/storyboard/s2/s2-b-vestibule.jpg',
      clip: 'video/storyboard/s2/s2-b-vestibule.mp4',
      clipStart: 2.4,
      alt: 'The failed electric bell beside the worn entry door.',
      shot: 'medium view of the vestibule fixtures',
      camera: 'slow continuous push in',
      action: 'attention shifts from the letter slot to the silent bell button',
      mood: 'O. Henry’s matter-of-fact comic detail',
      duration: 2.9,
      status: 'approved',
    },
    's2-7': {
      start: 'art/storyboard/s2/s2-b-vestibule.jpg',
      clip: 'video/storyboard/s2/s2-b-vestibule.mp4',
      clipStart: 5.3,
      alt: 'A worn name card appearing below the broken fixtures.',
      shot: 'close approach to the name card',
      camera: 'push in settling downward',
      action: 'the faded paper card becomes the visual focus',
      mood: 'faded dignity',
      duration: 2.4,
      status: 'approved',
    },
    's2-8': {
      start: 'art/storyboard/s2/s2-b-vestibule.jpg',
      clip: 'video/storyboard/s2/s2-b-vestibule.mp4',
      clipStart: 7.7,
      alt: 'The Youngs’ modest name card held beneath the broken letterbox.',
      shot: 'final fixture close-up',
      camera: 'nearly locked',
      action: 'the card and battered metalwork hold together in frame',
      mood: 'pride surviving neglect',
      duration: 2.3,
      status: 'approved',
    },
    's2-9': {
      start: 'art/storyboard/s2/s2-c-dillingham.jpg',
      clip: 'video/storyboard/s2/s2-c-dillingham.mp4',
      clipStart: 0,
      alt: 'A once-proud name card resting on a worn wooden table.',
      shot: 'still-life opening on the faded card',
      camera: 'slow continuous pan right',
      action: 'the long formal name begins the visual thought',
      mood: 'faded grandeur treated with affection',
      duration: 1.8,
      status: 'approved',
    },
    's2-10': {
      start: 'art/storyboard/s2/s2-c-dillingham.jpg',
      clip: 'video/storyboard/s2/s2-c-dillingham.mp4',
      clipStart: 1.8,
      alt: 'The faded card giving way to a modest pay envelope.',
      shot: 'period tabletop still life',
      camera: 'slow continuous pan right',
      action: 'the camera leaves the proud name and approaches the household money',
      mood: 'memory of better circumstances',
      duration: 1.7,
      status: 'approved',
    },
    's2-11': {
      start: 'art/storyboard/s2/s2-c-dillingham.jpg',
      clip: 'video/storyboard/s2/s2-c-dillingham.mp4',
      clipStart: 3.5,
      alt: 'A pay envelope and period coins suggesting the former thirty-dollar wage.',
      shot: 'close still life of envelope and coins',
      camera: 'slow continuous pan right',
      action: 'a fuller group of coins passes through focus',
      mood: 'prosperity remembered without nostalgia',
      duration: 2.1,
      status: 'approved',
    },
    's2-12': {
      start: 'art/storyboard/s2/s2-c-dillingham.jpg',
      clip: 'video/storyboard/s2/s2-c-dillingham.mp4',
      clipStart: 5.6,
      alt: 'A smaller present-day group of coins beside the worn pay envelope.',
      shot: 'tight tabletop comparison',
      camera: 'pan slowing toward a stop',
      action: 'the smaller coin group comes into sharp focus',
      mood: 'the quiet pressure of reduced income',
      duration: 2.2,
      status: 'approved',
    },
    's2-13': {
      start: 'art/storyboard/s2/s2-c-dillingham.jpg',
      clip: 'video/storyboard/s2/s2-c-dillingham.mp4',
      clipStart: 7.8,
      alt: 'The worn card, pay envelope, and few remaining coins sharing one frame.',
      shot: 'final still-life tableau',
      camera: 'nearly locked',
      action: 'the proud name and modest present circumstances resolve together',
      mood: 'gentle irony rather than humiliation',
      duration: 2.2,
      status: 'approved',
    },
    's2-14': {
      start: 'art/storyboard/s2/s2-d-homecoming.jpg',
      clip: 'video/storyboard/s2/s2-d-homecoming.mp4',
      clipStart: 0,
      alt: 'Jim arriving home to Della in their small furnished flat.',
      shot: 'wide two-person homecoming',
      camera: 'slow continuous pullback',
      action: 'Jim enters and Della immediately recognizes him',
      mood: 'weariness giving way to warmth',
      duration: 3.5,
      status: 'approved',
    },
    's2-15': {
      start: 'art/storyboard/s2/s2-d-homecoming.jpg',
      clip: 'video/storyboard/s2/s2-d-homecoming.mp4',
      clipStart: 3.5,
      alt: 'Della crossing the room and warmly embracing Jim.',
      shot: 'medium two-shot',
      camera: 'slow continuous pullback',
      action: 'Della reaches Jim and he returns her hug',
      mood: 'unguarded affection',
      duration: 2.8,
      status: 'approved',
    },
    's2-16': {
      start: 'art/storyboard/s2/s2-d-homecoming.jpg',
      clip: 'video/storyboard/s2/s2-d-homecoming.mp4',
      clipStart: 6.3,
      alt: 'Jim and Della holding each other in the humble room.',
      shot: 'settled embrace',
      camera: 'pullback easing to a stop',
      action: 'the embrace softens into familiar comfort',
      mood: 'love made ordinary and therefore convincing',
      duration: 2,
      status: 'approved',
    },
    's2-17': {
      start: 'art/storyboard/s2/s2-d-homecoming.jpg',
      clip: 'video/storyboard/s2/s2-d-homecoming.mp4',
      clipStart: 8.3,
      alt: 'The young couple together in their worn but affectionate home.',
      shot: 'final domestic tableau',
      camera: 'nearly locked',
      action: 'Jim and Della remain close as the room settles around them',
      mood: 'all very good',
      duration: 1.7,
      status: 'approved',
    },
    's3-0': {
      start: 'art/storyboard/s3/s3-a-window-della.jpg',
      alt: 'Della composing herself beside the winter window with the few saved coins in hand.',
      shot: 'quiet profile at the window',
      camera: 'still illustration',
      action: 'Della has attended to her tear-marked cheeks and gathers herself',
      mood: 'private sorrow under control',
      duration: 3.2,
      status: 'approved',
    },
    's3-1': {
      start: 'art/storyboard/s3/s3-a-window-della.jpg',
      alt: 'Della looking down at the little group of coins beside a gray winter window.',
      shot: 'same quiet window profile',
      camera: 'still illustration',
      action: 'her gaze drifts from the coins toward the gray backyard',
      mood: 'dull winter discouragement',
      duration: 2.2,
      status: 'approved',
    },
    's3-2': {
      start: 'art/storyboard/s3/s3-b-cat-fence.jpg',
      clip: 'video/storyboard/s3/s3-b-cat-fence.mp4',
      clipStart: 0,
      alt: 'A gray cat walking along a gray wooden fence in a snowy gray backyard.',
      shot: 'exterior profile of cat and fence',
      camera: 'subtle lateral tracking drift',
      action: 'the cat begins its careful walk along the fence rail',
      mood: 'gray-on-gray visual wit',
      duration: 2.6,
      status: 'approved',
    },
    's3-3': {
      start: 'art/storyboard/s3/s3-b-cat-fence.jpg',
      clip: 'video/storyboard/s3/s3-b-cat-fence.mp4',
      clipStart: 2.6,
      alt: 'The gray cat continuing across the wintry fence as Christmas approaches.',
      shot: 'continuation of the exterior profile',
      camera: 'subtle lateral tracking drift',
      action: 'the cat pads steadily toward the middle of the rail',
      mood: 'winter quiet before Christmas',
      duration: 2.6,
      status: 'approved',
    },
    's3-4': {
      start: 'art/storyboard/s3/s3-b-cat-fence.jpg',
      clip: 'video/storyboard/s3/s3-b-cat-fence.mp4',
      clipStart: 5.2,
      alt: 'The gray cat balanced on the fence above the poor winter yard.',
      shot: 'held exterior profile',
      camera: 'nearly locked tracking view',
      action: 'the cat keeps all four paws carefully on the narrow rail',
      mood: 'ordinary life under financial pressure',
      duration: 2.2,
      status: 'approved',
    },
    's3-5': {
      start: 'art/storyboard/s3/s3-b-cat-fence.jpg',
      clip: 'video/storyboard/s3/s3-b-cat-fence.mp4',
      clipStart: 7.4,
      alt: 'The gray cat nearing the far end of the fence in the snowy backyard.',
      shot: 'final exterior profile',
      camera: 'tracking drift settling to a stop',
      action: 'the cat completes its walk along the fence rail',
      mood: 'months of saving reduced to one small sum',
      duration: 2.6,
      status: 'approved',
    },
    's3-6': {
      start: 'art/storyboard/s3/s3-c-present-planning.jpg',
      clip: 'video/storyboard/s3/s3-c-present-planning.mp4',
      clipStart: 0,
      alt: 'Della beginning another careful count of the few coins at her table.',
      shot: 'intimate medium table view',
      camera: 'restrained continuous push',
      action: 'her fingertip returns to the first coin',
      mood: 'plain arithmetic and fatigue',
      duration: 1.1,
      status: 'approved',
    },
    's3-7': {
      start: 'art/storyboard/s3/s3-c-present-planning.jpg',
      clip: 'video/storyboard/s3/s3-c-present-planning.mp4',
      clipStart: 1.1,
      alt: 'Della separating the same meager coins on the worn tabletop.',
      shot: 'closer hands-and-coins view',
      camera: 'restrained continuous push',
      action: 'she separates the coins into a tiny group',
      mood: 'expenses exceeding every plan',
      duration: 1.2,
      status: 'approved',
    },
    's3-8': {
      start: 'art/storyboard/s3/s3-c-present-planning.jpg',
      clip: 'video/storyboard/s3/s3-c-present-planning.mp4',
      clipStart: 2.3,
      alt: 'Della facing the familiar result of another calculation.',
      shot: 'same intimate table view',
      camera: 'slow push toward her hands',
      action: 'her fingers pause over the unchanged total',
      mood: 'dry recognition',
      duration: 1.1,
      status: 'approved',
    },
    's3-9': {
      start: 'art/storyboard/s3/s3-c-present-planning.jpg',
      clip: 'video/storyboard/s3/s3-c-present-planning-v2.mp4',
      clipStart: 0,
      alt: 'The few coins and empty gift box before Della at the little table.',
      shot: 'coins and gift box sharing the frame',
      camera: 'restrained continuous push',
      action: 'Della gathers the coins near the empty box',
      mood: 'love pressed against an inadequate sum',
      duration: 5.75,
      status: 'approved',
    },
    's3-10': {
      start: 'art/storyboard/s3/s3-c-present-planning.jpg',
      clip: 'video/storyboard/s3/s3-c-present-planning-v2.mp4',
      clipStart: 5.75,
      alt: 'Della looking from the coins toward the empty box meant for Jim’s gift.',
      shot: 'medium table portrait',
      camera: 'restrained continuous push settling into a hold',
      action: 'her attention shifts from money to the imagined present',
      mood: 'happy plans remembered',
      duration: 4.292,
      status: 'approved',
    },
    's3-11': {
      start: 'art/storyboard/s3/s3-c-present-planning.jpg',
      clip: 'video/storyboard/s3/s3-c-present-planning.mp4',
      clipStart: 5.9,
      alt: 'Della reaching gently toward the small empty gift box.',
      shot: 'hands, coins, and box',
      camera: 'nearly locked close view',
      action: 'one hand leaves the coins and approaches the box',
      mood: 'a fine gift imagined',
      duration: 1.2,
      status: 'approved',
    },
    's3-12': {
      start: 'art/storyboard/s3/s3-c-present-planning.jpg',
      clip: 'video/storyboard/s3/s3-c-present-planning.mp4',
      clipStart: 7.1,
      alt: 'Della resting her hand at the edge of the empty box while thinking of Jim.',
      shot: 'intimate table detail',
      camera: 'locked',
      action: 'her fingertips settle at the box’s edge',
      mood: 'wanting something worthy',
      duration: 1.3,
      status: 'approved',
    },
    's3-13': {
      start: 'art/storyboard/s3/s3-c-present-planning.jpg',
      clip: 'video/storyboard/s3/s3-c-present-planning.mp4',
      clipStart: 8.4,
      alt: 'Della and the empty gift box held in a moment of tender resolve.',
      shot: 'final medium table portrait',
      camera: 'locked',
      action: 'she holds the box lightly and steadies herself',
      mood: 'Jim’s worth becoming a decision',
      duration: 1.6,
      status: 'approved',
    },
    's3-14': {
      start: 'art/storyboard/s3/s3-d-pier-glass.jpg',
      clip: 'video/storyboard/s3/s3-d-pier-glass.mp4',
      clipStart: 0,
      alt: 'Della standing beside the narrow pier glass between the windows.',
      shot: 'medium-full view of woman and narrow mirror',
      camera: 'nearly locked with a tiny push',
      action: 'Della considers the thin strip of reflected image',
      mood: 'observant domestic detail',
      duration: 1.6,
      status: 'approved',
    },
    's3-15': {
      start: 'art/storyboard/s3/s3-d-pier-glass.jpg',
      clip: 'video/storyboard/s3/s3-d-pier-glass.mp4',
      clipStart: 1.6,
      alt: 'The awkwardly narrow mirror revealing only part of Della at once.',
      shot: 'same mirror composition',
      camera: 'tiny deliberate push',
      action: 'the narrow reflection begins to slide as Della leans',
      mood: 'gentle O. Henry wit',
      duration: 1.6,
      status: 'approved',
    },
    's3-16': {
      start: 'art/storyboard/s3/s3-d-pier-glass.jpg',
      clip: 'video/storyboard/s3/s3-d-pier-glass.mp4',
      clipStart: 3.2,
      alt: 'Della making a small agile lean to find herself in the pier glass.',
      shot: 'medium-full mirror view',
      camera: 'nearly locked',
      action: 'she leans sideways by a few careful inches',
      mood: 'physical ingenuity without slapstick',
      duration: 1.6,
      status: 'approved',
    },
    's3-17': {
      start: 'art/storyboard/s3/s3-d-pier-glass.jpg',
      clip: 'video/storyboard/s3/s3-d-pier-glass.mp4',
      clipStart: 4.8,
      alt: 'Della’s correctly aligned reflection resolving through the narrow glass.',
      shot: 'woman and thin reflected slice',
      camera: 'locked',
      action: 'the reflection tracks her subtle shift in exact correspondence',
      mood: 'dry visual explanation',
      duration: 1.7,
      status: 'approved',
    },
    's3-18': {
      start: 'art/storyboard/s3/s3-d-pier-glass.jpg',
      clip: 'video/storyboard/s3/s3-d-pier-glass.mp4',
      clipStart: 6.5,
      alt: 'Della finding a nearly complete impression of herself in the narrow mirror.',
      shot: 'resolved mirror view',
      camera: 'locked',
      action: 'her lean settles into the useful viewing angle',
      mood: 'a ridiculous object mastered',
      duration: 1.7,
      status: 'approved',
    },
    's3-19': {
      start: 'art/storyboard/s3/s3-d-pier-glass.jpg',
      clip: 'video/storyboard/s3/s3-d-pier-glass.mp4',
      clipStart: 8.2,
      alt: 'Della standing calmly beside the narrow glass she has learned to use.',
      shot: 'final woman-and-mirror tableau',
      camera: 'locked',
      action: 'she straightens after the practiced shift',
      mood: 'quiet mastery',
      duration: 1.8,
      status: 'approved',
    },
    's3-20': {
      start: 'art/storyboard/s3/s3-e-hair-release.jpg',
      alt: 'Della turning decisively toward the narrow glass with her hair still pinned.',
      shot: 'full-figure transformation setup',
      camera: 'nearly locked',
      action: 'Della arrives before the glass and becomes suddenly still',
      mood: 'a decision arriving',
      duration: 1.5,
      status: 'approved',
    },
    's3-21': {
      start: 'art/storyboard/s3/s3-e-hair-release.jpg',
      alt: 'Della’s eyes brightening as she sees a possibility in the glass.',
      shot: 'same full-figure mirror view',
      camera: 'nearly locked',
      action: 'her gaze sharpens and both hands begin to rise',
      mood: 'brilliant sudden purpose',
      duration: 1.5,
      status: 'approved',
    },
    's3-22': {
      start: 'art/storyboard/s3/s3-e-hair-release.jpg',
      clip: 'video/storyboard/s3/s3-e-hair-release.mp4',
      clipStart: 3,
      alt: 'Della reaching for the pins in her compact brown bun, pale but resolute.',
      shot: 'full-figure mirror view with hands at hair',
      camera: 'locked',
      action: 'her hands find the pins as her expression turns resolute',
      mood: 'color draining into courage',
      duration: 1.8,
      status: 'approved',
    },
    's3-23': {
      start: 'art/storyboard/s3/s3-e-hair-release.jpg',
      clip: 'video/storyboard/s3/s3-e-hair-release.mp4',
      clipStart: 4.8,
      alt: 'Della rapidly drawing the pins from her long brown hair before the glass.',
      shot: 'uninterrupted full-figure hair release',
      camera: 'locked',
      action: 'the pins come free and the same hair begins to cascade',
      mood: 'swift irreversible resolve',
      duration: 2.2,
      status: 'approved',
    },
    's3-24': {
      start: 'art/storyboard/s3/s3-e-hair-release.jpg',
      alt: 'Della’s exceptionally long brown hair falling to nearly her knees before the glass.',
      shot: 'completed full-length hair tableau',
      camera: 'locked',
      action: 'the released hair settles at its full natural length in reality and reflection',
      mood: 'astonishment becoming sacrifice',
      duration: 3,
      status: 'approved',
    },
    's4-0': {
      start: 'art/storyboard/s4/s4-a-two-treasures.jpg',
      clip: 'video/storyboard/s4/s4-a-two-treasures.mp4',
      clipStart: 0,
      alt: 'Della and Jim’s inherited gold watch presented together as the Youngs’ two treasures.',
      shot: 'balanced room tableau with Della and the watch',
      camera: 'very slow push in',
      action: 'Della holds still while winter light settles across the room',
      mood: 'humble abundance',
      duration: 2.5,
      status: 'approved',
    },
    's4-1': {
      start: 'art/storyboard/s4/s4-a-two-treasures.jpg',
      clip: 'video/storyboard/s4/s4-a-two-treasures.mp4',
      clipStart: 2.5,
      alt: 'Della standing beside a table where Jim’s cherished gold watch rests.',
      shot: 'same balanced room tableau',
      camera: 'continuous slow push',
      action: 'the composition holds Della and the watch in equal regard',
      mood: 'quiet pride',
      duration: 2.5,
      status: 'approved',
    },
    's4-2': {
      start: 'art/storyboard/s4/s4-a-two-treasures.jpg',
      clip: 'video/storyboard/s4/s4-a-two-treasures.mp4',
      clipStart: 5,
      alt: 'Jim’s old gold pocket watch and leather strap on the worn table.',
      shot: 'watch-weighted room tableau',
      camera: 'continuous slow push',
      action: 'a restrained glint finds the inherited watch',
      mood: 'family history',
      duration: 2.5,
      status: 'approved',
    },
    's4-3': {
      start: 'art/storyboard/s4/s4-a-two-treasures.jpg',
      clip: 'video/storyboard/s4/s4-a-two-treasures.mp4',
      clipStart: 7.5,
      alt: 'Della’s exceptionally long brown hair glowing softly in the winter-lit flat.',
      shot: 'Della-weighted room tableau',
      camera: 'continuous slow push',
      action: 'the light traces the length and texture of Della’s hair',
      mood: 'living treasure',
      duration: 2.5,
      status: 'approved',
    },
    's4-4': {
      start: 'art/storyboard/s4/s4-b-sheba.jpg',
      clip: 'video/storyboard/s4/s4-b-sheba.mp4',
      clipStart: 0,
      alt: 'Della at the airshaft window with a playful royal shadow imagined across the way.',
      shot: 'imagined airshaft comparison',
      camera: 'locked',
      action: 'the distant jewel casket begins to shimmer beside the royal shadow',
      mood: 'affectionate exaggeration',
      duration: 3.2,
      status: 'approved',
    },
    's4-5': {
      start: 'art/storyboard/s4/s4-b-sheba.jpg',
      clip: 'video/storyboard/s4/s4-b-sheba.mp4',
      clipStart: 3.2,
      alt: 'Della’s long hair catching window light as an imagined queen looks on from shadow.',
      shot: 'same imagined airshaft comparison',
      camera: 'locked',
      action: 'a faint draft moves the long hair while the silhouette stays still',
      mood: 'playful grandeur',
      duration: 3.2,
      status: 'approved',
    },
    's4-6': {
      start: 'art/storyboard/s4/s4-b-sheba.jpg',
      clip: 'video/storyboard/s4/s4-b-sheba.mp4',
      clipStart: 6.4,
      alt: 'The imagined royal jewels dim beside the richness of Della’s brown hair.',
      shot: 'jewel-and-hair comparison',
      camera: 'locked',
      action: 'the last soft sparkles recede around the jewel casket',
      mood: 'the narrator’s warm joke',
      duration: 3.6,
      status: 'approved',
    },
    's4-7': {
      start: 'art/storyboard/s4/s4-c-solomon.jpg',
      clip: 'video/storyboard/s4/s4-c-solomon.mp4',
      clipStart: 0,
      alt: 'Jim’s hand holding his gold pocket watch before an imagined cellar of treasure.',
      shot: 'watch close-up with soft-focus fantasy',
      camera: 'shallow-focus hold',
      action: 'Jim steadies the old watch in his hand',
      mood: 'fond comic boasting',
      duration: 2.4,
      status: 'approved',
    },
    's4-8': {
      start: 'art/storyboard/s4/s4-c-solomon.jpg',
      clip: 'video/storyboard/s4/s4-c-solomon.mp4',
      clipStart: 2.4,
      alt: 'An old gold watch held before a dim treasure chest in an imagined basement.',
      shot: 'watch and treasure insert',
      camera: 'slow focus drift',
      action: 'the watch lid opens and catches a small glint',
      mood: 'treasure measured against treasure',
      duration: 2.4,
      status: 'approved',
    },
    's4-9': {
      start: 'art/storyboard/s4/s4-c-solomon.jpg',
      clip: 'video/storyboard/s4/s4-c-solomon.mp4',
      clipStart: 4.8,
      alt: 'Jim’s watch remaining bright as the imagined keeper of riches watches from behind.',
      shot: 'rack focus from watch toward the imagined king',
      camera: 'slow rack focus',
      action: 'attention begins to travel from the watch toward the bearded figure',
      mood: 'proud mischief',
      duration: 2.5,
      status: 'approved',
    },
    's4-10': {
      start: 'art/storyboard/s4/s4-c-solomon.jpg',
      clip: 'video/storyboard/s4/s4-c-solomon.mp4',
      clipStart: 7.3,
      alt: 'The imagined King Solomon touching his beard in envy of Jim’s heirloom watch.',
      shot: 'bearded figure revealed beyond the watch',
      camera: 'focus completes in the background',
      action: 'the imagined king gives his beard one small envious touch',
      mood: 'the boast lands',
      duration: 2.7,
      status: 'approved',
    },
    's4-11': {
      start: 'art/storyboard/s4/s4-d-hair-cascade.jpg',
      alt: 'Della standing before the pier glass with her long brown hair released around her.',
      shot: 'quiet full-figure hair portrait',
      camera: 'still hold',
      action: 'the completed cascade is allowed to breathe without another action',
      mood: 'wonder before sacrifice',
      duration: 2.5,
      status: 'approved',
    },
    's4-12': {
      start: 'art/storyboard/s4/s4-d-hair-cascade.jpg',
      alt: 'Della’s brown hair rippling in long waves like dark water.',
      shot: 'same full-figure hair portrait',
      camera: 'still hold',
      action: 'the eye follows the repeated waves of the hair',
      mood: 'lyrical abundance',
      duration: 2.5,
      status: 'approved',
    },
    's4-13': {
      start: 'art/storyboard/s4/s4-d-hair-cascade.jpg',
      alt: 'Della’s hair reaching below her knees before the narrow glass.',
      shot: 'same full-figure hair portrait',
      camera: 'still hold',
      action: 'the frame makes the extraordinary length unmistakable',
      mood: 'astonished admiration',
      duration: 2.5,
      status: 'approved',
    },
    's4-14': {
      start: 'art/storyboard/s4/s4-d-hair-cascade.jpg',
      alt: 'Della almost wrapped in her own long brown hair like a natural garment.',
      shot: 'same full-figure hair portrait',
      camera: 'still hold',
      action: 'the still composition lets the hair read as a garment',
      mood: 'beauty at the edge of loss',
      duration: 2.5,
      status: 'approved',
    },
    's4-15': {
      start: 'art/storyboard/s4/s4-e-repin.jpg',
      clip: 'video/storyboard/s4/s4-e-repin.mp4',
      clipStart: 0,
      alt: 'Della nervously gathering her long hair before the pier glass.',
      shot: 'continuous repinning action',
      camera: 'slow move from full figure toward medium',
      action: 'Della gathers and pins the long hair with both hands',
      mood: 'nervous resolve',
      duration: 5.2,
      status: 'approved',
    },
    's4-16': {
      start: 'art/storyboard/s4/s4-e-repin-end.jpg',
      alt: 'Della finishing the compact bun and becoming still beside her reflection.',
      shot: 'settled medium portrait beside the pier glass',
      camera: 'still hold after the cut-safe end of the action',
      action: 'the finished bun and lowered hands hold without a continuity jump',
      mood: 'a momentary falter',
      duration: 2.4,
      status: 'approved',
    },
    's4-17': {
      start: 'art/storyboard/s4/s4-e-repin-end.jpg',
      alt: 'Della standing tearful and still above the worn red carpet.',
      shot: 'tear tableau beside the pier glass',
      camera: 'still ending',
      action: 'the tear tableau holds after the repinning action',
      mood: 'quiet cost accepted',
      duration: 2.4,
      status: 'approved',
    },
  },
  media: {
    audio: 'magi-audio/',
    cues: 'cues/magi.vtt',
  },
};
